# Generated by Django 4.1.3 on 2022-12-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_pictures'),
        ),
    ]
